language: php
php:
    - 5.5
    - 5.6

install:
  - mkdir -p temp
  - mkdir -p log
  - rm app/config/config.local.neon
  - cp app/config/config.test.neon app/config/config.local.neon

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script: "vendor/bin/codecept run"
